server:
  port: 9991
#dubbo配置
dubbo:
  application:
    name: produce
    qos-enable: false
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.sun.dubba
  protocol:
    port: 20882
